### ISSUE TITLE
When using environmental variables to configure migration if no matching env variable found no error is presented

### ISSUE THREAD

**Issue by kudresov** [sequelize/cli#115]
Overview
Version affected: 1.5.0
DB connector: postgres

Repro steps

create configuration like:

``` JSON
{
  "develop": {
    "use_env_variable": "DATABASE_URL"
  },
  "production": {
    "use_env_variable": "DATABASE_URL"
  }
}
```

Export two environmental variables:

``` bash
export NODE_ENV=development
export DATABSE_URL=ANY_CORRECT_URL
```

_Note: `NODE_ENV` is misspelled on purpose_

Run command:
`sequelize db:migrate`

Output:
It will complaint that MySql connector is not found, even though we are not using MySql. This error message is very misleading.

Expected Output:
An error message saying that you can't find a corresponding environment configuration

This error occurs because `config-helper` in `readConfig` method returns an object with all environments rather than throwing an exception.

**Comment by kudresov** [comment]
If I get some time I will try to setup the project on my machine and fix the bug myself.

**Comment by idan** [comment]
Just got bitten by this.

**Comment by sushantdhiman** [comment]
Its fixed in v3 

```bash
Sequelize CLI [Node: 6.11.2, CLI: 3.0.0-3, ORM: 4.8.2]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "config/config.json".
Using environment "development".

ERROR: Error parsing url: undefined
```

**Comment by jmnyarega** [comment]
I am still getting the same error using sequelize: 5.21.5 & sequelize: 5.5.1

**Comment by Farhan-Haseeb** [comment]
I am still getting the same error using sequelize: 5.22.0
